insert INTO categoria(nombre, descripcion, nemonico, fecha) VALUES ('TIPO USUARIO', 'TIPO DE USUARIO', 'TIPO_USUARIO', CURRENT_TIMESTAMP);
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('EMPLEADO', 'EMPLEADO', 'EMPLEADO', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='TIPO_USUARIO'));
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('EXTERNO', 'EXTERNO', 'EXTERNO', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='TIPO_USUARIO'));

insert INTO categoria(nombre, descripcion, nemonico, fecha) VALUES ('PRODUCTOS', 'PRODUCTOS', 'PRODUCTOS', CURRENT_TIMESTAMP);
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('CAMISETAS', 'CAMISETAS', 'CAMISETAS', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='PRODUCTOS'));
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('VASOS', 'VASOS', 'VASOS', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='PRODUCTOS'));
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('COMICS', 'COMICS', 'COMICS', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='PRODUCTOS'));
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('JUGUETES', 'JUGUETES', 'JUGUETES', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='PRODUCTOS'));
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('ACCESORIOS MARVEL', 'ACCESORIOS MARVEL', 'ACCESORIOS_MARVEL', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='PRODUCTOS'));
insert INTO categoria(nombre, descripcion, nemonico, fecha, padre_id) VALUES ('ACCESORIOS DC COMICS', 'ACCESORIOS DC COMICS', 'ACCESORIOS_DCCOMICS', CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='PRODUCTOS'));

INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('CAMISETA SPIDERMAN', 'BONITO ESTAMPADO', 'icon-camiseta', 20, 12.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='CAMISETAS'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('CAMISETA TOR', 'BONITO ESTAMPADO POSTERIOR', 'icon-camiseta-tor', 10, 5.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='CAMISETAS'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('VASO TRANSPARENTE', 'VASO TRANSPARENTE', 'icon-vaso', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='VASOS'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('VASO PLASTICO', 'VASO TRANSPARENTE', 'icon-vaso', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='VASOS'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('VASO LOGOTIPO', 'VASO LOGOTIPO', 'icon-vaso-logo', 40, 2.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='VASOS'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('COMIC IROMAN', 'COMIC IROMAN', 'icon-ironman', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='COMICS'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('COMIC CAPITAN AMERICA', 'COMIC CAPITAN AMERICA', 'icon-america-comic', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='COMICS'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('JUGUETE PAYASO', 'UGUETE PAYASO', 'icon-payaso', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='JUGUETES'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('SOLDADITO', 'SOLDADITO', 'icon-soldado', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='JUGUETES'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('MARTILLO DE TOR', 'MARTILLO DE TOR', 'icon-martillo', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='ACCESORIOS_MARVEL'));
INSERT INTO producto(nombre, descripcion, icon, cantidad, valor_unitario, fecha, estado, cat_id) VALUES ('BATISEÑAL', 'BATISEÑAL', 'icon-batisenial', 40, 3.2, CURRENT_TIMESTAMP, TRUE, (SELECT cat_id FROM categoria WHERE nemonico='ACCESORIOS_MARVEL'));
	
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='VASO PLASTICO'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 20, 0, 20, 12.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='CAMISETA SPIDERMAN')); 
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 10, 0, 20, 5.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='CAMISETA TOR'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='VASO TRANSPARENTE'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 2.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='VASO LOGOTIPO'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='COMIC IROMAN'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='COMIC CAPITAN AMERICA'));

INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='JUGUETE PAYASO'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='SOLDADITO'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='MARTILLO DE TOR'));
INSERT INTO stock(observacion, cantidad, cantidad_anterior, cantidad_actual, valor_unitario, fecha_entrada, fecha_salida, estado, pro_id) values('INICIO', 40, 0, 40, 3.2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, (SELECT pro_id FROM producto WHERE nombre='BATISEÑAL'));
	
INSERT INTO usuario(nombre, login, clave, estado, fecha, tipo_usuario) VALUES ('EDWIN CAILLAMARA', '1304569098', 'DFdrtrtr/tuyu.', TRUE, CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='EMPLEADO'));
INSERT INTO usuario(nombre, login, clave, estado, fecha, tipo_usuario) VALUES ('DAYSI CHANGO', '1304009001', 'ABdrtrtr/fgyu.', TRUE, CURRENT_TIMESTAMP, (SELECT cat_id FROM categoria WHERE nemonico='EXTERNO'));
